### ISSUE TITLE
White Screen on PC

### ISSUE THREAD

**Issue by mrgreezy3** [Rinnegatamante/VITA2PC#13]
When Launhing Vita2pc 64bit client i recieve a white screen after inputing my ip address. I Can hear all Audio From PC but Cannot See Video On PC . Window is All white (i had this same issue with rincheats streamer)

BorderLands USA Version is the game... 

Thank you For your time

**Comment by Rinnegatamante** [comment]
Use lower quality in the config menu.
If the problem persists, you're starting PC client before Vita stream or you've messed up with DLL files.

**Comment by bobby5d** [comment]
Having the same problem every game I try shows a white screen but can hear audio
tried asynchronous, quality worst and no audio then pressing start stream then opening it on pc
also tried the lowmem version and dont use any memory plugins

**Comment by Rinnegatamante** [comment]
Have you tried some games already added to the compatibility list?

**Comment by WreckingBerserker** [comment]
Hi guys i guess its related to the graphics driver/card because when i tested it in another pc with regularly updated drivers it worked fine
this is not a bug in the plugin itself

**Comment by Rinnegatamante** [comment]
It's kinda strange that SDL doesn't pop an error in the console btw. It seems an openGL related issue.

**Comment by WreckingBerserker** [comment]
Yeah,Open Gl is one of the main stuff in Graphics Card Driver so i guess updating/upgrading it would solve the problem
