### ISSUE TITLE
PC-side controller support

### ISSUE THREAD

**Issue by ghost** [Rinnegatamante/VITA2PC#15]
Seeing how it works now, we'd have to listen on yet another port. I started trying to accomplish this locally [but for some reason it won't compile](https://ghostbin.com/paste/nhr33/raw) (even before trying said changes).

**Comment by Rinnegatamante** [comment]
You must manually compile libjpeg-turbo fixing such errors:

https://github.com/Rinnegatamante/VITA2PC/blob/master/psvita/encoder.c#L4-L8

**Comment by ghost** [comment]
Whoops didn't spot that, thanks.
