### ISSUE TITLE
H-encore support?

### ISSUE THREAD

**Issue by Disinterpreter** [Rinnegatamante/VITA2PC#22]
I tried install, but h-encore was crashed.

**Comment by M2l2koPOWER** [comment]
bump

**Comment by Odel** [comment]
Looks like the hook addresses need updated in main.c

Not sure how to do this, but it should be trivial for someone

**Comment by Rinnegatamante** [comment]
I don't have a 2nd PSVITA to mess with h-encore and i'm not even remotely going to update my main one to anything higher than 3.60.

I'm actually looking for a good deal to get a 2nd PSVITA but, until i found one, i won't be able to work on whatever issues related to h-encore support.

**Comment by Rinnegatamante** [comment]
The plugin works perfectly on fw > 3.60. Tested personally.
