### ISSUE TITLE
Any new development?

### ISSUE THREAD

**Issue by detlion1643** [Rinnegatamante/VITA2PC#24]
Hello,

I'm curious if there is or will be any new development with this plugin? I tried it, using it under *ALL and loading the game World of Final Fantasy crashes the Vita to the point it turns off. I've seen the compatibility list and it's very short. I myself think it would be tedious to constantly find and add game title id's under the config file, and if they don't work, have to remove them. I'd even like to stream homebrew titles and apps (like adrenaline for psp games).

I have seen the usb streaming plugin, but can't use that when I use my grip (it's a Nyko that extends the battery and the usb doesn't passthrough the data pins).

**Comment by DvaMishkiLapa** [comment]
_Install the .suprx plugin and put it under *TITLEID where TITLEID is the game where you want to use it (NOTE: Do NOT use *ALL cause it will cause a freeze on enso bootup due to incompatibility with Livearea (*main).)_
https://wololo.net/talk/viewtopic.php?t=48459
